import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link
          href="/"
          className=" absolute top-4 left-4 text-white text-[0.8rem] rounded-full bg-none border border-white  px-4 py-2"
        >
          Home
        </Link>
        {children}
      </body>
    </html>
  );
}
